# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FillGaps
                                 A QGIS plugin
 This plugin is intended to fill gaps and holes in a polygon layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-28
        copyright            : (C) 2025 by Antonio Sobral Almeida
        email                : 66124.almeida@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Antonio Sobral Almeida'
__date__ = '2025-10-28'
__copyright__ = '(C) 2025 by Antonio Sobral Almeida'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FillGaps class from file FillGaps.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fill_gaps import FillGapsPlugin
    return FillGapsPlugin()
